### ISSUE TITLE
Annotating a Python class doesn't produce anything

### ISSUE THREAD

**Issue by badrbouslikhin** [danymat/neogen#100]
Hello,

When I try to annotate any Python class, nothing happens (not even an error). It works fine with methods though.
Using `:Neogen` on the following code (with the cursor anywhere on the first line) produces nothing:
```python
class Foo:
    def __init__(self, bar):
        self.bar = bar

    def baz(self):
        return None
```

I expected:
```python
class Foo:
    """

    Attributes: 
    	bar: 
    """
    def __init__(self, bar):
        self.bar = bar

    def baz(self):
        return None
```

Any ideas?

**Comment by danymat** [comment]
Hello, this is weird. Can you share your neogen config ?

**Comment by danymat** [comment]
From what I see, `ft` does indeed prevent annotations. You can try to remove it and just keep `event` as your main lazy loading method.

**Comment by spareslant** [comment]
I got the following error message while trying to annotate python class
`
E5108: Error executing lua .../0.7.2_1/share/nvim/runtime/lua/vim/treesitter/query.lua:185: attempt to index local 'node' (a nil value)
stack traceback:
        .../0.7.2_1/share/nvim/runtime/lua/vim/treesitter/query.lua:185: in function 'get_node_text'
        ...ack/packer/start/neogen/lua/neogen/utilities/helpers.lua:32: in function 'get_node_text'
        ...packer/start/neogen/lua/neogen/configurations/python.lua:188: in function 'extract'
        .../site/pack/packer/start/neogen/lua/neogen/granulator.lua:34: in function 'granulator'
        ...m/site/pack/packer/start/neogen/lua/neogen/generator.lua:226: in function 'generate'
        [string ":lua"]:1: in main chunk
`

**Comment by mosmuell** [comment]
@danymat I think this issue shouldn't be closed. I also get the same error @spareslant mentioned and @badrbouslikhin himself wrote that removing `ft` doesn't fix it. Is there a way around it or even a fix that wasn't mentioned here?

**Comment by mauricekraus** [comment]
I also get this issue, I additionally tried changing the snippet engine to luasnip. 
```lua
self.neogen.setup {
		-- snippet_engine = "luasnip",
		enabled = true,
		languages = { python = {
			template = {
				annotation_convention = "google_docstrings",
			},
		} },
	}
```

Same error message.
