### ISSUE TITLE
Why three dash for lua docgen

### ISSUE THREAD

**Issue by oeyoews** [danymat/neogen#101]
![image](https://user-images.githubusercontent.com/72405338/174488504-368b88ae-2685-4d60-9315-c6bd72b3a001.png)

When use this command `Neogen file` to generate annotation, I alway get this warning, 

Why not this

```lua
--- xxx
-- @module
-- @author
-- @licence
```

**Comment by danymat** [comment]
Hello, by default Neogen uses emmylua annotations for lua. From your screenshot, I see that the required annotation is luadoc.

You can specify ldoc as your default lua annotation (see https://github.com/danymat/neogen#configuration)
