### ISSUE TITLE
reST Python docstrings: Requesting a new option to disable types, and for Neogen to add info about exceptions

### ISSUE THREAD

**Issue by sseneca** [danymat/neogen#106]
I'm using reST docstrings for Python and then generating documentation via Sphinx.

Say I have this function:

```python
def test(a: int) -> int:
    if a == 0:
        raise Exception
    return a
```

Calling Neogen (configured to use reST) gives me this:

```python
def test(a: int) -> int:
    """[TODO:description]

    :param a: [TODO:description]
    :type a: int [TODO:description]
    :return: [TODO:return]
    :rtype: [TODO:return]
    """
    if a == 0:
        raise Exception
    return a
```

First, since I'm already using type hints as defined in [PEP 484](https://peps.python.org/pep-0484/), I use [sphinx-autodoc-typehints](https://github.com/tox-dev/sphinx-autodoc-typehints) which means I can write docstrings as follows:

```python
def test(a: int) -> int:
    """[TODO:description]

    :param a: [TODO:description]
    :return: [TODO:return]
    """
    if a == 0:
        raise Exception
    return a
```

The rest is redundant; Sphinx figures out the types on its own.

Second, why doesn't it add anything about the `Exception`? Ideally, I'd like the autogenerated docstring to look like this:

```python
def test(a: int) -> int:
"""[TODO:description]

:param a: [TODO:description]
:raises Exception: [TODO:description]
:return: [TODO:return]
"""
if a == 0:
    raise Exception
return a
```

Thanks 🙂

**Comment by danymat** [comment]
Hello, can you try the version 2.9.2 ? Concerning the Exception, i will take a look at that and i ping you

**Comment by danymat** [comment]
Added support for the throw statements too

**Comment by danymat** [comment]
> Like I said above, rtype shouldn't be there

Yes, i fixed uniquely the first issue.
THe process for rtype is still ungoing

**Comment by danymat** [comment]
> The raises should have the specific error/exception, not just "error"

Concerning this issue, can you provide me a snippet of code that reproduces the issue and that i could test ?

**Comment by danymat** [comment]
The `ouch` bypass is not that simple to bypass, in fact:

- The syntax tree of the call to a function in a raise is not the same as raising a Parameter. I'm still not sure that those two are only the allowed raises.

**Comment by danymat** [comment]
Yes, none parameters are not generated 

Concerning the last point, if it's really high value for you I can take a look 
Or we can wait for other people to have the same need
