### ISSUE TITLE
Luasnip breaks indentation annotation in python

### ISSUE THREAD

**Issue by sirutBuasai** [danymat/neogen#108]
When specifying `snippet_engine = "luasnip"`, the annotation is not indented. I have not tested this in other languages but is currently broken in python.

With `snippet_engine = "luasnip"`
<img width="416" alt="Screen Shot 2022-09-13 at 21 16 21" src="https://user-images.githubusercontent.com/73297481/190037081-122b30c0-8e64-4092-85b5-93cab553c14a.png">

With `snippet_engine = nil`
<img width="335" alt="Screen Shot 2022-09-13 at 21 16 45" src="https://user-images.githubusercontent.com/73297481/190037099-4d6dbd58-7315-4a7e-bd34-f1a34d87b9af.png">

**Comment by h0adp0re** [comment]
Can confirm the same for JavaScript.

**Comment by ffiiddeelliittyy** [comment]
I'm encountering the same issue as Sirut in Python.

**Comment by danymat** [comment]
Hello everyone, i had to get a loong time of because of moving out and starting a new work. I will look into the issue very soon, and i will write a message if I need more user input ❤️

**Comment by danymat** [comment]
Concerning your issue, it seems that luasnip did some breaking change. WIll look closely

**Comment by yriveiro** [comment]
I also hit this issue. This is my config

```lua
n.setup {
  snippet_engine = 'luasnip',
  languages = {
    python = {
      template = {
        annotation_convention = 'numpydoc', -- for a full list of annotation_conventions, see supported-languages below,
      },
    },
  },
}
```

**Comment by Elkiders99** [comment]
Hi! found this issue with python.

Took the liberty of finding which LuaSnip commit introduced the issue:
c4f7e797376c8e3ab6f848bd6bc5d33019fea5e1

Hope this helps!

**Comment by Elkiders99** [comment]
Opened #110 to fix this!

**Comment by danymat** [comment]
Hello, the fix was provided and is now on main, thanks @Elkiders99 !
You can all update the app, or put a "2.8.1" tag to your plugin manager.
