### ISSUE TITLE
Neogen not working for me in Typescript

### ISSUE THREAD

**Issue by loeschg** [danymat/neogen#113]
New to this library/plugin, and I'm having trouble getting it to work with Typescript. 

The following is what I'm seeing using a bare Neovim setup with packer, Treesitter (with typescript installed), and neogen. It keeps generating documentation at the top of the file. 

Any suggestions for troubleshooting?

https://user-images.githubusercontent.com/766021/200135549-0eb2e332-f39c-459b-ae14-e45c9f71e13f.mov

**Comment by jemag** [comment]
I can reproduce the problem on my side too. It has been a while since I have done Typescript, but I do believe that it used to work before.

**Comment by danymat** [comment]
Hello, then it's probably an update of the parser, really possible and that's the only point that it's not possible for me to automatize
If someone has an idea to make it future proof in queries update, I would gladly take your consideration 

But from this specific bug, I will take a look and update the queries from the new parser 
Thanks for letting me know, I keep you updated

**Comment by jemag** [comment]
I also doubt it is possible to fully make it future proof.

One possible idea would be to have GitHub workflows run on parsers update and execute specific tests verifying that the behavior of Neogen with the newly updated parsers is still proper. In case of a failing workflow you would get notified instantly. 

Obviously there will still be work to be done to fix the problem, but at least that could provide a way to be aware instantly.

That's the only idea I got.

**Comment by danymat** [comment]
Hello, my bad and it was totally unrelated with TS, but with one of my previous fixes: #111 . I did a fallback of function classes to 0,0 if a special use case was not attained. You can see in the commit how small it is lol.

Sorry for the inconvenience and please tell me if the bug is fixed. Cheers

**Comment by jemag** [comment]
@danymat working great so far for me. Thanks for the fix
