### ISSUE TITLE
python reST

### ISSUE THREAD

**Issue by hyawara** [danymat/neogen#119]
![image](https://user-images.githubusercontent.com/31959238/206694312-3765ac23-8a01-4586-ac6d-156aa752be85.png)

![image](https://user-images.githubusercontent.com/31959238/206694531-1bd3f033-2a29-4b39-89f1-2b035efaf226.png)

## **use \<leader\>nf** -->

![image](https://user-images.githubusercontent.com/31959238/206694905-c9c19035-367e-4034-b0eb-798ef96cfef9.png)

**Comment by danymat** [comment]
In the `":return "`, try to add `":return %s"`. Putting `%s` does get the string grabbed by the locator

**Comment by danymat** [comment]
Well I don't know what's the problem here. Can you go in explaining what you wanna have and what is not working for you ?

**Comment by hyawara** [comment]
I think I know why, ha ha, my reasons, thank you very much for your reply

**Comment by danymat** [comment]
You welcomed 🙌❤️
