### ISSUE TITLE
support ft=cpp.doxygen

### ISSUE THREAD

**Issue by tastytea** [danymat/neogen#122]
I'm using `ft=cpp.doxygen` (instead of the default `cpp`) as a [workaround because tree-sitter does not have doxygen support yet](https://github.com/tree-sitter/tree-sitter-cpp/issues/116). Neogen complains that “Language cpp.doxygen not supported.” It would be nice if you could add it. 💖

If you don't want to, please consider adding information on how to alias a filetype to the docs. This worked for me:

```lua
require('neogen').setup({
    languages = {
        ['cpp.doxygen'] = require('neogen.configurations.cpp')
    }
})
```

**Comment by danymat** [comment]
Wow, i was not aware that annotations were supported by tree-sitter! I see jsdoc in your url too
TS support for annotations could be used to automatically sync and update created annotations (#65)

**Comment by danymat** [comment]
Done, thank you for your input! Added the code snippet to the Readme as of right now
