### ISSUE TITLE
Support for Moonscript

### ISSUE THREAD

**Issue by PhosCity** [danymat/neogen#123]
Is it possible to add support for [moonscript](https://github.com/leafo/moonscript)? It's a language that compiles to lua so anything that works for lua should work for moonscript.

**Comment by danymat** [comment]
Hello ! Do they have a Tree-sitter grammar ? I can't find it on nvim-treesitter :/
Moreover, if moonscript TS is based around Lua parser, you can use #122 technique

**Comment by PhosCity** [comment]
I only found out after I created this issue about the treesitter grammar. I have created a request at nvim-treesitter for moonscript. Hopefully it gets added.

Until then, I'll use the technique you mentioned.
