### ISSUE TITLE
Doc: Snippet usage and example

### ISSUE THREAD

**Issue by theoo** [danymat/neogen#130]
The [documentation](https://github.com/danymat/neogen#snippet-support) states that there is snippets support with different engines available, but examples are not provided, for `luasnip` for instance.

It would be very handy to get an example to override an existing snippet for instance. In my case, I would change YARD comments from:
```
# [TODO:description]
```

to 

```
#
# [TODO:something_else]
#
```
Because this is a convention in our project.

Overriding the template with "#\n# [TODO:description]\n#" won't work for indented lines, so I'm hoping that snippets can help this.

Best regards

**Comment by danymat** [comment]
Hello, sorry for the huge delay lmao.
For the placeholder text, you can take a look at :h neogen-configuration where you can modify the placeholders:

![image](https://github.com/user-attachments/assets/def0f826-4cfa-4a0c-a66c-abf944a2fc2d)

For the lines before and after, you'll need to modify the template annotation and pass your own. Check `:h neogen-annotation` for how to do it. Suppose you take the YARD one: https://github.com/danymat/neogen/blob/main/lua/neogen/templates/yard.lua

To have your example, I would replace with something like:

```lua
local i = require("neogen.types.template").item

return {
    { nil, "# $1", { no_results = true, type = { "class", "func" } } },
    { nil, "#", { no_results = true, type = { "type" } } }, -- Note the addition here
    { nil, "# $1", { no_results = true, type = { "type" } } },
    { nil, "#", { no_results = true, type = { "type" } } },  -- Note the addition here
    { nil, "#" }, -- Same
    { nil, "# $1" },
    { nil, "#" }, -- Same
    { i.Parameter, "# @param %s [$1] $1", {} },
    { i.Return, "# @return [$1] $1", {} },
}
```

I will close the issue, but don't hesitate to reopen :)
