### ISSUE TITLE
Add Throw Support For Python Google Style (Raises:)

### ISSUE THREAD

**Issue by ColinKennedy** [danymat/neogen#137]
Heya, just wanted to say I'm a big fan of this plug-in and love that it hooks into LuaSnip. It has quickly become my daily driver for docstrings

I saw https://github.com/danymat/neogen/issues/106 and specifically in the `init.lua`

```
--- ## 2.10.0~
---   - Add support for Throw statements in python
---     Note: only active for reST template as of right now (please open an issue request for more templates)
```

I'd like to add Throw statements for google_docstring and have already made a fork which so far has been working well for me.

I don't know this code-base very well but gave a try [making a fork + diff](https://github.com/danymat/neogen/commit/8fe698ef508513f0c7dcdcf1731e554d482da070) and it seems to work as expected.

```diff
+    { i.HasThrow, "", { type = { "func" } } },
+    { i.HasThrow, "Raises:", { type = { "func" } } },
+    { i.Throw, "    %s: $1", { type = { "func" } } },
```

## Before
```python
def test(a: int) -> int:
    if a == 0:
        raise ValueError("test")

    return a
```

## After `:Neogen`
```python
def test(a: int) -> int:
    """[TODO:description]

    Args:
        a: [TODO:description]

    Raises:
        ValueError: [TODO:throw]

    Returns:
        [TODO:return]
    """
    if a == 0:
        raise ValueError("test")

    return a
```

With permission, I would like to make a PR with the new change applied.

**Comment by danymat** [comment]
Heyo @ColinKennedy, thanks a lot for being fan of it, me too I'm a big fan of it and it saved me hours when i had to comment code, on every language I've written. (the most complete specs in neogen are the languages i developed a lot)

Thanks for the addition, I didn't know at the time that google docstrings had a `Raises:` statement. Gonna check the PR in a bit
