### ISSUE TITLE
Duplicate @return tag in phpdoc

### ISSUE THREAD

**Issue by stormherz** [danymat/neogen#138]
Hi!

First of all, thanks for the great plugin! 

I'm having an issue with phpdoc comment for a class method. While generating doc block for `method`:

```php
<?php

class Some {
    public function method($arg)
    {
        if ($arg == 10) {
            return 10;
        }

        return 10;
    }
}
``` 

it generates the following (`@return` tag is duplicated):

```phpdoc
    /**
     * 
     *
     * @param  $arg 
     * @return 
     * @return 
     */
```

Interesting thing is if we're removing that `if` or adding additional returns - it will generate proper phpdoc block, without `@return` duplication

**Comment by danymat** [comment]
Hello, 

Thanks for the catch ! I think I have fixed it for php language :)
