### ISSUE TITLE
Python type annotation missing

### ISSUE THREAD

**Issue by Nachtalb** [danymat/neogen#140]
I may be doing something wrong here, but I can't get neogen to generate type annotations in the docstrings. 

I have setup a minimal nvim config to test it out: https://gist.github.com/Nachtalb/036a48b995eb1dabec1e5f6cfad2a8e7

Maybe I was too blind to see a specific config. 

If I change this https://github.com/danymat/neogen/blob/9c17225aac94bdbf93baf16e1b2d2c6dcffb0901/lua/neogen/templates/google_docstrings.lua#L17 line to: 

```lua
{ { i.Parameter, i.Type }, "    %s (%s): $1", { required = i.Tparam, type = { "func" } } },
```

Here is the difference between the first and the second: 

```python
def this_is_a_test(some_string: str, foo: int, bar: dict[str, tuple[str, float]] | None = None) -> str:
    """[TODO:description]

    Args:
        some_string: [TODO:description]
        foo: [TODO:description]
        bar: [TODO:description]

    Returns:
        [TODO:return]
    """
    return "test"
```

```python
def this_is_a_test(some_string: str, foo: int, bar: dict[str, tuple[str, float]] | None = None) -> str:
    """[TODO:description]

    Args:
        some_string (str): [TODO:description]
        foo (int): [TODO:description]
        bar (dict[str, tuple[str, float]] | None): [TODO:description]

    Returns:
        [TODO:return]
    """
    return "test"
```

If you need any more information please do not hesitate to ask me.

**Comment by Forthoney** [comment]
Not a contributor, but what's wrong with the second instance?

**Comment by Nachtalb** [comment]
@Forthoney 
Nothing, that's the point. 

The first one is the one shipped by Neogen. The second one is the one I modified myself in the source file of Neogen. IMHO, it should set the types but default, but maybe it can already do that somehow, and I have something wrongly configured, which is the question here.

**Comment by Forthoney** [comment]
Thanks for clarifying. I agree with you that the second case should be the default behavior
