### ISSUE TITLE
Exclude bare-returns from generated Python docstrings

### ISSUE THREAD

**Issue by ColinKennedy** [danymat/neogen#144]
Bare-returns, returns with no explicit value, are used for control flow. Caller functions aren't meant to assign from a function with no explicit return.

e.g.

```python
def set_foo(self, value):
    if not value:
        return

    self._foo = value
```

However Neogen will generate a `Returns:` block for these bare-returns

```python
def set_foo(self, value):
    """[TODO:description]

    Args:
        value ([TODO:parameter]): [TODO:description]

    Returns:
        [TODO:return]
    """
    if not value:
        return

    self._foo = value
```

![neogen_bare_return_python_demonstration](https://github.com/danymat/neogen/assets/10103049/f936df9d-a3e7-40c1-9c66-76e945952b8c)

Neogen should detect these empty, bare-returns and prevent them from showing up in the docstring.

**Comment by danymat** [comment]
Hello, i'm okay with this, gonna merge it
