### ISSUE TITLE
Incorrect parameter list in Python

### ISSUE THREAD

**Issue by ColinKennedy** [danymat/neogen#148]
When you have a parameter that takes an identifier as a default value, the default value shows up as a parameter in the docstring, which it should not.

https://github.com/danymat/neogen/assets/10103049/6ec11348-55b0-46e9-99ba-7cdf11864e94

I took a try at fixing this myself by changing `retrieve = "all"` to `retrieve = "first"` and was surprised to find that didn't simply work

`lua/neogen/configurations/python.lua`
```diff
                                subtree = {
                                    { retrieve = "all", node_type = "identifier", extract = true, as = i.Parameter },
                                    {
                                        retrieve = "all",
                                        node_type = "default_parameter",
                                        subtree = {
                                            {
-                                               retrieve = "all",
+                                               retrieve = "first",
                                                node_type = "identifier",
                                                extract = true,
                                                as = i.Parameter,
                                            },
                                        },
                                    },
```

This issue may require someone more familiar with the codebase to take a look :)

**Comment by danymat** [comment]
`retrieve` is used in `matching_nodes_from()` in `nodes.lua`.
`retrieve = "first"` will only get the first recursive element it finds, but it will not be used as `recursive = false` in this case. See here: https://github.com/danymat/neogen/blob/d8c8145304190b1889452b50ef437d9d49bdc033/lua/neogen/utilities/nodes.lua#L80-L83

It's my fault, as the documentation does not seem precise.

To fix this specific bug, i instead used `position = 1` to get the child node at the first position.

**Comment by ColinKennedy** [comment]
Oh I see, that makes more sense to have that as a separate argument. It's been such a breath of fresh air to use this repo, btw. Every other docstring generator project I've tried had lots of dependencies or hard to understand codebases. And it re-uses snippet engines instead of rolling its own. Neogen is my favorite, by far. Thank you for making it!
