### ISSUE TITLE
Feature Request - Support NeoVim native snippet engine

### ISSUE THREAD

**Issue by weilbith** [danymat/neogen#161]
Hey 👋🏾 

NeoVim has quite recently merged an implementation for basic snippet support based on the LSP specification. Which should be sufficient I guess. Would be definitely nice to use this plugin without any other additional plugin. 🙃

**Comment by danymat** [comment]
Hey, thanks for @sachnr, support for vim.snippet engine has been added. Just change your config option to `snippet_engine = "nvim"`

**Comment by weilbith** [comment]
Hey ✌🏾 
Sorry for the late feedback. Thank you very much for implementing that feature! 🙏🏾
