### ISSUE TITLE
Update / Correction command

### ISSUE THREAD

**Issue by Willem-J-an** [danymat/neogen#166]
After I update a function signature I would like to run the doc generate command, or perhaps like an update command. What I'd like it to do is update my docstring parameter names that were changed, but retain the other documentation that was written. Can this be done with the current feature set of the plugin?
Thanks!

**Comment by ColinKennedy** [comment]
Related? https://github.com/danymat/neogen/issues/165

**Comment by Willem-J-an** [comment]
Didn't see that one, seems similar enough
