### ISSUE TITLE
Need unittests

### ISSUE THREAD

**Issue by ColinKennedy** [danymat/neogen#173]
I found 2 bugs in Neogen, came to report it, and then saw someone else already did. https://github.com/danymat/neogen/pull/171

And it was a bug I'd added while fixing another. Unittests are definitely needed for all these lovely edge-cases

**Comment by amenrio** [comment]
Small world! I'm currently watching your Rez Academy's playlist. I was trying to learn Rez by myself just to extend my knowledge and learn how things might work in bigger studios and I was a little stuck with all the new concepts, but your playlist has helped me understand them a little bit better. Thank you so much!
