### ISSUE TITLE
Option to always disable writing argument types in Python

### ISSUE THREAD

**Issue by kiyoon** [danymat/neogen#176]
In modern python scripts, most of the time I wouldn't need to write types in docstrings because they are already part of the language.  
In neogen, it sees if the function is typed and puts types.

For example, below (or similar) is what neogen generates.

```python
def foo_without_type(a):
    """
    Args:
        a ():
    """

def foo(a: str):
    """
    Args:
        a: 
    """
```

However, even if a method has no types I always want to disable types in docstring as I would rather put them in the method.

Is there a way to set up the plugin like that?

**Comment by danymat** [comment]
Hello, of course, you can customize all annotation conventions to suit your needs, even create your custom one. Take a look at `:h neogen-annotation` in the docs to have a look on how to customize your annotation.

If you want just a small modification to google_docstrings, copy the contents of the file located in `lua/neogen/templates/google_docstrings.lua` to your configuration (as explained in the docs)

Change L16 (https://github.com/danymat/neogen/blob/b2942f546c28fb27525dbdad8656549b9a28c846/lua/neogen/templates/google_docstrings.lua#L16) to something like:

```lua
    { i.Parameter, "    %s: $1", { type = { "func" } } },
```

**Comment by kiyoon** [comment]
Thank you! I didn't know about this but now it makes sense. Thanks for helping :)
