### ISSUE TITLE
neogen doesn't work correctly for C

### ISSUE THREAD

**Issue by cryptomilk** [danymat/neogen#18]
The following example only creates parameter documentation for `bool from_cmdline`.

```
/**
 * @brief
 *
 * @param[in] from_cmdline
 * @returns
 */
static bool set_logfile(TALLOC_CTX *mem_ctx,
                        struct loadparm_context *lp_ctx,
                        const char *log_basename,
                        const char *process_name,
                        bool from_cmdline)
{
}
```

**Comment by danymat** [comment]
Hello @cryptomilk, 

I think I just fixed the error (the recursive method was not doing it's best job).
Can you check if the error persists ?

Feel free to close if it's fixed, and thank you for using the plugin and sharing the issue!

**Comment by cryptomilk** [comment]
Works fine, thank you!
