### ISSUE TITLE
Support annotating interfaces

### ISSUE THREAD

**Issue by mikehaertl** [danymat/neogen#182]
I can not add documentation to interfaces (at least in java and PHP - probably also no other language). It would be nice if this was supported.

Here's a screenshot of the corresponding treesitter tree:
![image](https://github.com/user-attachments/assets/981019a2-754c-4ff7-9e83-9875e468622b)

**Comment by mikehaertl** [comment]
@danymat what do you think about adding this for other languages, too?

Or is there a reason why it should *not* be possible to add documentation to an interface?

**Comment by danymat** [comment]
> @danymat what do you think about adding this for other languages, too?
> 
> Or is there a reason why it should _not_ be possible to add documentation to an interface?

I'm OK with adding support to interfaces to conventions that support them. It's just that's been overlooked and we forgot to add support to it
