### ISSUE TITLE
Help implementing doctrings for Julia

### ISSUE THREAD

**Issue by cristobaltapia** [danymat/neogen#184]
Hi,

thanks for this nice plugin :). 

I was trying to implement docstrings for Julia by following the tutorial in [[1]](https://github.com/danymat/neogen/blob/main/docs/adding-languages.md) but I am having problems getting the parameters of the function. From the tree I can only extract the signature for some reason. Probably is something about treesitter that I don't understand. Here is my code until now:

```lua
local nodes_utils = require("neogen.utilities.nodes")
local extractors = require("neogen.utilities.extractors")

local parent = {
  func = { "function_definition" },
  file = { "module_definition" },
  type = { "typed_expression", "identifier" },
  class = { "struct_definition" },
}

local common_function_extractor = function(node)
  local tree = {
    {
      retrieve = "first",
      node_type = "signature",
      extract = true,
      subtree = {
        position = 1,
        node_type = "call_expression",
        extract = true,
        subtree = {
          retrieve = "first",
          node_type = "argument_list",
          subtree = {
            { retrieve = "all", node_type = "identifier", extract = true },
          },
        },
      },
    },
  }

  local nodes = nodes_utils:matching_nodes_from(node, tree)
  local res = extractors:extract_from_matched(nodes)

  return {
    parameters = res.identifier,
    signature = res.signature,
  }
end

local data = {
  func = {
    ["function_definition"] = {
      ["0"] = {
        extract = common_function_extractor,
      },
    },
  },
}

return {
  parent = parent,
  data = data,
  template = {
    annotation_convention = "julia",
    use_default_comment = false,
    julia = {
      { nil, '"""' },
      -- Signature
      { "signature", "    %s", { type = { "func" } } },
      { nil, "" },
      -- Description
      { nil, "$1" },
      { nil, "" },

      -- Arguments
      { nil, "# Arguments" },
      { "parameters", "- `%s`: $1" },
      { nil, '"""' },
    },
  },
}

```

I can test this with the following function:
```julia
function test(a, b)
    c = a + b
    return c
end
```

And I get:
```julia
"""
    test(a, b)



# Arguments
"""
function test(a, b)
    c = a + b
    return c
end
```

Do you have any advice about what might be the problem?

Thanks!

[1] https://github.com/danymat/neogen/blob/main/docs/adding-languages.md

**Comment by danymat** [comment]
Hello, 

Thanks for your feedback :)
What should be the desired output ? 

Furthermore, an old PR was in draft for Julia support : https://github.com/danymat/neogen/pull/84 did you get to see it ?

**Comment by cristobaltapia** [comment]
I've been playing a bit with #84 and now I can generate the docstring. Some node_types needed to be updated. If I get it to work correctly for all cases, then I could make a PR (or continue the other PR... is that even possible?)

**Comment by danymat** [comment]
> I've been playing a bit with #84 and now I can generate the docstring. Some node_types needed to be updated. If I get it to work correctly for all cases, then I could make a PR (or continue the other PR... is that even possible?)

For sure, yes, I think you can continue the other PR, but you can create your own without any problem. Take a look at the other existing configuration files (except python, because it's a very huge one) for some examples on what works well.

Test cases were just added to Neogen (take a look at https://github.com/danymat/neogen/blob/fef1ab3932f724ec558d2498e92a0ce6933c2c79/tests/neogen/lua_emmylua_spec.lua for a simple example). After creating the file, add `julia` here: https://github.com/danymat/neogen/blob/fef1ab3932f724ec558d2498e92a0ce6933c2c79/tests/minimal_init.lua#L25C1-L25C35 and run `make test`.
