### ISSUE TITLE
Add support for C++

### ISSUE THREAD

**Issue by Shatur** [danymat/neogen#19]
The plugin is currently supports C, can we enable it for C++?

**Comment by danymat** [comment]
Hello, sure we could, but I'm not sure the tree sitter queries are the same. I'll try to look into that

**Comment by Shatur** [comment]
Should be partially same because C++ contains `; inherits: c` in treesitter highlighting:
https://github.com/nvim-treesitter/nvim-treesitter/blob/0e25e0e98990803e95c7851236e43b3ee934d443/queries/cpp/highlights.scm#L1

**Comment by Shatur** [comment]
It works, thanks!
But some additional stuff missing, like information about templates.

**Comment by danymat** [comment]
Nice, so that means we can use the c configuration language, and apply more stuff for cpp.

> But some additional stuff missing, like information about templates.

What do you mean ? I need some extra information, or a snippet to reproduce it

**Comment by Shatur** [comment]
Quick example for testing: https://github.com/crow-translate/crow-translate/blob/400c2432e37f64e7c65b5fd87add02ce5b34a005/src/mainwindow.h#L159

Should contains `tparam`.

**Comment by Shatur** [comment]
And related question. I noticed that all params generated with `[in]`. Is this expected? For example, the following function:

```cpp
    void test(int &value);
```

Generates:

```cpp
    /**
     * @brief 
     *
     * @param[in] value 
     */
```

But it should be:

```cpp
    /**
     * @brief 
     *
     * @param[out] value 
     */
```

But I think that you can't detect it with Treesitter. Could we generate it without direction annoation?

```cpp
    /**
     * @brief 
     *
     * @param[in] value 
     */
```

But it should be:

```cpp
    /**
     * @brief 
     *
     * @param value 
     */
```

**Comment by danymat** [comment]
> Quick example for testing: https://github.com/crow-translate/crow-translate/blob/400c2432e37f64e7c65b5fd87add02ce5b34a005/src/mainwindow.h#L159
> 
> Should contains `tparam`.

Added support for variadic functions in cpp, you can try it and tell me

**Comment by danymat** [comment]
> And related question. I noticed that all params generated with `[in]`. Is this expected? For example, the following function:
> 
> ```c++
>     void test(int &value);
> ```
> 
> Generates:
> 
> ```c++
>     /**
>      * @brief 
>      *
>      * @param[in] value 
>      */
> ```
> 
> But it should be:
> 
> ```c++
>     /**
>      * @brief 
>      *
>      * @param[out] value 
>      */
> ```
> 
> But I think that you can't detect it with Treesitter. Could we generate it without direction annoation?
> 
> ```c++
>     /**
>      * @brief 
>      *
>      * @param value 
>      */
> ```

About this, I don't really now, it was being worked in this PR: https://github.com/danymat/neogen/pull/14
Do you have any links I could use to know what's `[in]` and `[out]` ?

**Comment by Shatur** [comment]
> Added support for variadic functions in cpp (as simple as doing this: e4e09d6 !), you can try it and tell me.

Thank you, It works!
But I meant to add `tparam`: https://www.doxygen.nl/manual/commands.html#cmdtparam

>  Do you have any links I could use to know what's [in] and [out] ?

That is the problem. It is not always possible to tell. If you are passing something by pointer, it can be either `input` or `output`. I would suggest to remove direction specification at all. It is optional.

**Comment by danymat** [comment]
> That is the problem. It is not always possible to tell. If you are passing something by pointer, it can be either input or output.

I see. I think it'll be very difficult to get the information, as I would need to see if the parameter is being written to. 
It's feasible, but not quite at the moment because it means adding some checks in the generator.
I will remove them, but if someone wants to create a basic fetcher for it, I'm totally okay

**Comment by Shatur** [comment]
>  I will remove them

Yep, this would be the best solution for now.

**Comment by Shatur** [comment]
Found another issue. If I try to generate the documentation for the following function:

https://github.com/crow-translate/crow-translate/blob/400c2432e37f64e7c65b5fd87add02ce5b34a005/src/mainwindow.h#L69

I get this:

```cpp
    /*  */
    QKeySequence closeWindowShortcut() const;
```

**Comment by danymat** [comment]
> Quick example for testing: https://github.com/crow-translate/crow->  translate/blob/400c2432e37f64e7c65b5fd87add02ce5b34a005/src/mainwindow.h#L159>

> Should contains tparam.

Is it supposed to supercharge a function ? 

I get this from Treesitter: 

<img width="475" alt="Capture d’écran 2021-11-08 à 20 22 19" src="https://user-images.githubusercontent.com/5306901/140804510-cd267120-27b2-4c40-8807-2ba016b206a6.png">

If it's a type by it's own, I can create a new type for this, called `template` (see https://github.com/danymat/neogen#usage for more details about types in neogen)

**Comment by danymat** [comment]
> ```c++
> QKeySequence closeWindowShortcut() const;
> ```

What should I get instead ?

**Comment by Shatur** [comment]
> What should I get instead ?

```cpp
    /**
     * @brief 
     *
     * @return 
     */
```

**Comment by Shatur** [comment]
Looks like here are two separate issues.
1. Generation of empty comment `/*  */` happens if the function doesn't have any arguments.
2. If return type isn't void it should generate `@return` after all params.

**Comment by danymat** [comment]
> Looks like here are two separate issues.
> 
> 1. Generation of empty comment `/*  */` happens if the function doesn't have any arguments.
> 2. If return type isn't `void`, the documentation should have `@return` after all params.

I don't think it's an issue, it's a feature:

https://github.com/danymat/neogen/blob/d04b657c88105e119475c594d11be956391bab25/lua/neogen/configurations/c.lua#L109-L117

I mean, Treesitter does not tell me there is a return in your code snippet:
<img width="401" alt="Capture d’écran 2021-11-08 à 20 31 37" src="https://user-images.githubusercontent.com/5306901/140805761-ade1875b-1b66-47b1-95d0-f00a49fe4358.png">

**Comment by Shatur** [comment]
> I mean, Treesitter does not tell me there is a return in your code snippet:

If a declaration contains a type first, then it's a return value. Or do you think that this is a Treesitter bug?

> Generation of empty comment /* */ happens if the function doesn't have any arguments.

But this probably shouldn't happen? We should always have a `@brief` even if the function doesn't have any arguments.

**Comment by Shatur** [comment]
> But this probably shouldn't happen? We should always have a @brief even if the function doesn't have any arguments.

Here is an example of a function without a return type: https://github.com/crow-translate/crow-translate/blob/400c2432e37f64e7c65b5fd87add02ce5b34a005/src/mainwindow.h#L145

**Comment by Shatur** [comment]
To be more clear I expecting to get the following:

```cpp
    /**
     * @brief 
     */
```

Instead of

```cpp
/* */
```

**Comment by danymat** [comment]
> If a declaration contains a type first, then it's a return value. Or do you think that this is a Treesitter bug?

No I think I should add this feature on my end. But I do want to check if this is written in doxygen. Can you hint me a place where they confirm this ?

**Comment by danymat** [comment]
> To be more clear I expecting to get the following:
> 
> ```c++
>     /**
>      * @brief 
>      */
> ```
> 
> Instead of
> 
> ```c++
> /* */
> ```

Modified template in last commit e87b4a2

**Comment by Shatur** [comment]
> Modified template in last commit e87b4a2

Thanks, now looks as expected!

> No I think I should add this feature on my end. But I do want to check if this is written in doxygen. Can you hint me a place where they confirm this ?

If a function have `void` return type, then there shouldn't be `@return`. In other case it should contains `@return`.
Here is an example: https://github.com/crow-translate/QOnlineTranslator/blob/33a53bf29a096c967b8e51ebccf70c02a94ab1c3/src/qonlinetranslator.h#L243
The documentation of this repo is validated on CI.

**Comment by Shatur** [comment]
> If a function have void return type, then there shouldn't be @return. In other case it should contains @return.
Here is an example: https://github.com/crow-translate/QOnlineTranslator/blob/33a53bf29a096c967b8e51ebccf70c02a94ab1c3/src/qonlinetranslator.h#L243
The documentation of this repo is validated on CI.

Should I close it and open another issue about `@return`?

**Comment by danymat** [comment]
> > If a function have void return type, then there shouldn't be @return. In other case it should contains @return.
> > Here is an example: https://github.com/crow-translate/QOnlineTranslator/blob/33a53bf29a096c967b8e51ebccf70c02a94ab1c3/src/qonlinetranslator.h#L243
> > The documentation of this repo is validated on CI.
> 
> Should I close it and open another issue about `@return`?

Yes, be sure to reference useful snippets to alleviate testing

**Comment by Shatur** [comment]
Done, thanks!
