### ISSUE TITLE
Python: Should Raises be after Return in google style?

### ISSUE THREAD

**Issue by hassec** [danymat/neogen#193]
I noticed that the generated doc always has the `Raises:` section before `Returns:`. If I understand correctly, this is due to the current template looking like:

https://github.com/danymat/neogen/blob/4b22542b96712a5a901fa909b7dc749251ae1625/lua/neogen/templates/google_docstrings.lua#L22-L26

The [Google Style Guide](https://google.github.io/styleguide/pyguide.html#doc-function-raises) has `Raises:` after `Returns:` in all examples. 

Should we follow the pattern suggested in the style guide and move `Raises:` after `Returns:`?

**Comment by danymat** [comment]
Seems to be the way 
I confirm we can change it the other way around then
