### ISSUE TITLE
Rust support

### ISSUE THREAD

**Issue by Shatur** [danymat/neogen#20]
It would be nice to support it.

**Comment by danymat** [comment]
Hello, do you have any annotation standards to recommend ?
And I don't know any of rust language, so it could be awesome if you specify me some functions I can use to try generating docs from.

**Comment by Shatur** [comment]
Oh, looks like it not needed for Rust, it generates everything automatically: https://doc.rust-lang.org/rust-by-example/meta/doc.html

I'm new to the language, sorry :)

**Comment by danymat** [comment]
No problem, we will reopen this issue if some people ask us to do it in neogen's way 🥂
