### ISSUE TITLE
Add template type for cpp

### ISSUE THREAD

**Issue by danymat** [danymat/neogen#21]
> Quick example for testing: https://github.com/crow-translate/crow->  translate/blob/400c2432e37f64e7c65b5fd87add02ce5b34a005/src/mainwindow.h#L159>

> Should contains tparam.

Is it supposed to supercharge a function ? 

I get this from Treesitter: 

<img width="475" alt="Capture d’écran 2021-11-08 à 20 22 19" src="https://user-images.githubusercontent.com/5306901/140804510-cd267120-27b2-4c40-8807-2ba016b206a6.png">

If it's a type by it's own, I can create a new type for this, called `template` (see https://github.com/danymat/neogen#usage for more details about types in neogen)

_Originally posted by @danymat in https://github.com/danymat/neogen/issues/19#issuecomment-963497358_

**Comment by danymat** [comment]
Any feedback @Shatur ?

**Comment by Shatur** [comment]
> Is it supposed to supercharge a function ?

Yes, It's like a regular function.

**Comment by Shatur** [comment]
Example:

```cpp
    /**
     * @brief Write a single value of type @p T to file
     *
     * @tparam T must not be a container type
     * @param data value to be written
     * @param bigEndian endianness
     */
    template<class T>
    void write(T data, bool bigEndian = false)
```

**Comment by danymat** [comment]
Added option in fa472f6, can you check if it works ? Your snippet allowed me to add optional params too

**Comment by Shatur** [comment]
> Added option in fa472f6, can you check if it works ? Your snippet allowed me to add optional params too

Awesome, thanks.

But sometimes there can be variadic temlate parameters like this:

```cpp
    template<typename Func, typename... Args>
    void buildDelayedOcrState(QState *state, Func buildState, Args... additionalArgs);
```

Is is possible to convert it into the following:

```
    /**
     * @brief
     *
     * @tparam Func
     * @tparam Args
     * @param state
     * @param buildState
     * @param additionalArgs
     */
```
?

**Comment by danymat** [comment]
It should be working now !
If everything good, we can close this issue

**Comment by Shatur** [comment]
Works, thanks you!

I noticed that if I put my cursor to the function definition - it skips template parameters. Is this expected?

**Comment by Shatur** [comment]
Also I noticed that you added templates support into `configurations/c.lua`. I think it's okay to handle C and C++ stuff using a single `configuration`. But just wanted you to know that it's only a C++ feature.

**Comment by danymat** [comment]
> Also I noticed that you added templates support into configurations/c.lua. I think it's okay to handle C and C++ stuff using a single configuration. But just wanted you to know that it's only a C++ feature.

Yes I know.
I'm using the fact that C++ contains the same and more node types than C, so that shouldn't be a problem

> I noticed that if I put my cursor to the function definition - it skips template parameters. Is this expected?

If you move the cursor out of the inserted region, you cannot go back and cycle to the annotations again

**Comment by Shatur** [comment]
>  I'm using the fact that C++ contains the same and more node types than C, so that shouldn't be a problem

Yes, I totally agree.

> If you move the cursor out of the inserted region, you cannot go back and cycle to the annotations again

Not sure If we understand each other. Let me describe it a little more. If my cursor (`|`) is here:

```cpp
    template<class T>
    void |write(T data, bool bigEndian = false)
```

I have the following (`tparam` is missing):

```cpp
    /**
     * @brief Write a single value of type @p T to file
     *
     * @param data value to be written
     * @param bigEndian endianness
     */
```

But If I put my cursor here:

```cpp
    |template<class T>
    void write(T data, bool bigEndian = false)
```

It will generate the following:

```
    /**
     * @brief Write a single value of type @p T to file
     *
     * @tparam T must not be a container type
     * @param data value to be written
     * @param bigEndian endianness
     */
```

**Comment by danymat** [comment]
Yes, it is normal. It'll locate the very next node from where your cursor is. That's why I was thinking in moving the template generation into it's own type, to avoid conflicts with functions

**Comment by Shatur** [comment]
Then it's okay, let's left everything as is. I think we can close the issue.

**Comment by danymat** [comment]
Nice, thank you
