### ISSUE TITLE
Return types in C++

### ISSUE THREAD

**Issue by Shatur** [danymat/neogen#22]
## Issue description

Currently the plugin generates `@returns` for `return_statement`. But sometimes it doesn't work.

## Examples

No return type:

```cpp
    /**
     * @brief Cancel translation operation (if any).
     */
    void abort();
```

Return type present.

```cpp
    /**
     * @brief Check translation progress
     *
     * @return `true` when the translation is still processing and has not finished or was aborted yet.
     */
    bool isRunning() const;
```

## Additional notes

Doxygen understands [@return](https://www.doxygen.nl/manual/commands.html#cmdreturn) and [@returns](https://www.doxygen.nl/manual/commands.html#cmdreturns). But I would suggest to go with `@return`, since `@returns` is just an alias to `@return`.

**Comment by danymat** [comment]
Can you try updating the plugin and checking out ?

**Comment by Shatur** [comment]
I think you get me wrong. We shouldn't have `@return` for void and should have it in all other cases.

**Comment by Shatur** [comment]
Examples:

Instead of:

```
    /**
     * @brief 
     *
     * @return 
     */
    void test();
```

We should have:

```
    /**
     * @brief 
     */
    void test();
```

**Comment by danymat** [comment]
I don't quite get it:
- you don't want return when the return type is void ? (It was previously implemented though)
- what else ?

**Comment by Shatur** [comment]
> you don't want return when the return type is void ? (It was previously implemented though)

Yes.
But it need it for all other return types (didn't worked before).

**Comment by danymat** [comment]
Okay so I just apply those changes ? https://github.com/danymat/neogen/issues/22#issuecomment-966090603

**Comment by Shatur** [comment]
Yes, I think so :)

**Comment by danymat** [comment]
Can you test the last changes ?

**Comment by Shatur** [comment]
It works, but now only for primitive types.
For example, this works as expected: 

```cpp
    /**
     * @brief Check translation progress
     *
     * @return `true` when the translation is still processing and has not finished or was aborted yet.
     */
    bool isRunning() const;
```

But this doesn't:

```cpp
    /**
     * @brief 
     */
    QToolButton swapButton();
```

Should be like this:

```cpp
    /**
     * @brief 
     *
     * @return 
     */
    QToolButton swapButton();
```

**Comment by danymat** [comment]
Hello @Shatur, can you try the fix provided ?

**Comment by Shatur** [comment]
Now everything is awesome, thank you!
