### ISSUE TITLE
C++: Function doesn't recognized sometimes

### ISSUE THREAD

**Issue by Shatur** [danymat/neogen#23]
## Example:

```cpp
class Shortcut
{
public:
    void processEvent(const XKeyEvent &event) const;
};
```

Annotation generation for `processEvent` results to nothing.

**Comment by danymat** [comment]
Do you have treesitter playground installed ? If not I will not be able to analyse it until tomorrow

**Comment by Shatur** [comment]
> Do you have treesitter playground installed ?

Yes. I think this is because the function is a field:

```cpp
class_specifier [0, 0] - [4, 1]
  name: type_identifier [0, 6] - [0, 14]
  body: field_declaration_list [1, 0] - [4, 1]
    access_specifier [2, 0] - [2, 7]
    field_declaration [3, 4] - [3, 52]
      type: primitive_type [3, 4] - [3, 8]
      declarator: function_declarator [3, 9] - [3, 51]
        declarator: field_identifier [3, 9] - [3, 21]
        parameters: parameter_list [3, 21] - [3, 45]
          parameter_declaration [3, 22] - [3, 44]
            type_qualifier [3, 22] - [3, 27]
            type: type_identifier [3, 28] - [3, 37]
            declarator: reference_declarator [3, 38] - [3, 44]
              identifier [3, 39] - [3, 44]
        type_qualifier [3, 46] - [3, 51]
```

**Comment by danymat** [comment]
Hmm.. what happens when you place your cursor over the function name and try to generate the functions annotation ?

**Comment by Shatur** [comment]
> Hmm.. what happens when you place your cursor over the function name and try to generate the functions annotation ?

Nothing happens.

**Comment by danymat** [comment]
Try adding `field_declaration`

Here: https://github.com/danymat/neogen/blob/96a597b7c02bcc438de5beac7c0e8f42380b63c4/lua/neogen/configurations/c.lua#L94

And here: https://github.com/danymat/neogen/blob/96a597b7c02bcc438de5beac7c0e8f42380b63c4/lua/neogen/configurations/c.lua#L99

**Comment by Shatur** [comment]
Worked, thanks. Opened a PR.
