### ISSUE TITLE
Bug in C++ template parsing 

### ISSUE THREAD

**Issue by flanggut** [danymat/neogen#26]
The current parsing of C++ template parameters has an issue. I think the current processing is looking for *any* parent node that is a `template_declaration`. However, if the function is within a class, the class itself can have a parent `template_declaration` which is then wrongfully used as the template declaration for the function.

Consider the following example:

```
template <typename D> class Foo {
public:
  float bar(float a) { return a; }
};
```
which has a tree like this:

```
template_declaration [0, 0] - [3, 2]
  parameters: template_parameter_list [0, 9] - [0, 21]
    type_parameter_declaration [0, 10] - [0, 20]
      type_identifier [0, 19] - [0, 20]
  class_specifier [0, 22] - [3, 1]
    name: type_identifier [0, 28] - [0, 31]
    body: field_declaration_list [0, 32] - [3, 1]
      access_specifier [1, 0] - [1, 7]
      function_definition [2, 2] - [2, 34]
        type: primitive_type [2, 2] - [2, 7]
        declarator: function_declarator [2, 8] - [2, 20]
          declarator: field_identifier [2, 8] - [2, 11]
          parameters: parameter_list [2, 11] - [2, 20]
            parameter_declaration [2, 12] - [2, 19]
              type: primitive_type [2, 12] - [2, 17]
              declarator: identifier [2, 18] - [2, 19]
        body: compound_statement [2, 21] - [2, 34]
          return_statement [2, 23] - [2, 32]
            identifier [2, 30] - [2, 31]
```

The parent template declaration is assigned to the function definition, even though it belongs to the class.

**Comment by flanggut** [comment]
As an example for this header file:

```
#pragma once

template <typename D> class Foo {
public:
  float bar(float a) { return a; }
};
```

And with the cursor on `bar`, I am getting documentation like this when I call `generate`:

```
#pragma once

/**
 * @brief 
 *
 * @tparam D 
 * @param a 
 */
template <typename D> class Foo {
public:
  /**
   * @brief 
   *
   * @param a 
   * @return 
   */
  float bar(float a) { return a; }
};
```

As a side note: I think the root node might not be considered at all, so I had to create a different root with `#pragma once`.

**Comment by danymat** [comment]
I don't think I understand correctly... In order for me to understand, can you do a snippet of what the current generation is doing, and what the annotation should look like ?

**Comment by flanggut** [comment]
I already did. If you take the snippet from my previous comment
```
#pragma once

template <typename D> class Foo {
public:
  float bar(float a) { return a; }
};

```
and you generate annotations for the function `bar` you get two annotations, one for the function and a wrong one for the class `Foo`.

**Comment by flanggut** [comment]
Specifically this is what I get
```

#pragma once

/**
 * @brief 
 *
 * @tparam D 
 * @param a 
 */
template <typename D> class Foo {
public:
  /**
   * @brief 
   *
   * @param a 
   * @return 
   */
  float bar(float a) { return a; }
};

```
And this is what I would expect
```

#pragma once

template <typename D> class Foo {
public:
  /**
   * @brief 
   *
   * @param a 
   * @return 
   */
  float bar(float a) { return a; }
};

```

**Comment by danymat** [comment]
Oh yeah right, it's a bug indeed

**Comment by danymat** [comment]
Hello once again, this should fix the bug that caused those multiple annotations. Can you check again ?

**Comment by flanggut** [comment]
Looks great! Thanks 👍
