### ISSUE TITLE
support for tsx files

### ISSUE THREAD

**Issue by axyz** [danymat/neogen#28]
not sure if I'm missing some configuration, but the plugin does not seem to work with `tsx` files (filetype=typescriptreact).

If I manually change the filetype to typescript it correctly adds an annotation.

treesitter is working correctly on both filetypes.

**Comment by axyz** [comment]
I think as a starting point this line:
https://github.com/danymat/neogen/blob/main/lua/neogen.lua#L133

could be duplicated to match `typescriptreact` as well. Not sure if there may be a need for a different configuration to handle jsx syntax though.

**Comment by danymat** [comment]
Hello!

Yes you can use this to add support for the language, you can use this and tell me if everything is the same

**Comment by danymat** [comment]
Check out the readme, you can kinda override the default setup function and add the language

**Comment by danymat** [comment]
Does this file use other types like vue format (that does use JavaScript and html)?
