### ISSUE TITLE
Support file-level annotations

### ISSUE THREAD

**Issue by thetic** [danymat/neogen#31]
ie `require('neogen').generate({type='file'})`

- https://www.doxygen.nl/manual/commands.html#cmdfile
- https://google.github.io/styleguide/pyguide.html#382-modules

**Comment by danymat** [comment]
This can be a very good idea. Do the filenames  need special convention ? (Python Modules, etc)

**Comment by thetic** [comment]
I don't know about *every* convention but here are examples. AFAICT they all place at the top of the file.

## Doxygen (C/C++) 

https://www.doxygen.nl/manual/docblocks.html#docexamples

```c
/** @file structcmd.
    @brief A Documented file.
    
    Details.
*/
```

The actual filename can (and probably should) be omitted.

## Google Docstrings (Python)

- https://google.github.io/styleguide/pyguide.html#382-modules

- https://www.sphinx-doc.org/en/master/usage/extensions/example_google.html#example-google

```python
"""A one line summary of the module or program, terminated by a period.

Leave one blank line.  The rest of this docstring should contain an
overall description of the module or program.  Optionally, it may also
contain a brief description of exported classes and functions and/or usage
examples.

  Typical usage example:

  foo = ClassFoo()
  bar = foo.FunctionBar()
"""

## Numpy (Python)

https://www.sphinx-doc.org/en/master/usage/extensions/example_numpy.html

## JSDoc

https://jsdoc.app/tags-module.html

**Comment by thetic** [comment]
Ldoc: https://stevedonovan.github.io/ldoc/examples/four.lua.html

**Comment by danymat** [comment]
Hello @thetic, I added the support for this new type, called `file`. Can you try it out ?

Currently supported:
- [x] c/cpp
- [ ] Python
- [ ] JS/TS
- [ ] Lua

**Comment by danymat** [comment]
Okay there is still one bug: It will start inserting at the first line not null

**Comment by danymat** [comment]
I added support for every annotation you provided. It's documented, and added in README. Can you try out ?

**Comment by meijieru** [comment]
> This can be a very good idea. Do the filenames need special convention ? (Python Modules, etc)
> 
> Edit:
> 
> It is entirely possible, but I need to be sure these file annotations are always on top. If so, we just need to set annotations on line 0, and we don't need TS parsing.

I think it is not the case for python at least.
For example, there may be `#!/usr/bin/env python3` following by the docstring.

**Comment by danymat** [comment]
@meijieru, referenced commit should do the job !

**Comment by thetic** [comment]
This is working great! Thank you!
