### ISSUE TITLE
Command API

### ISSUE THREAD

**Issue by Shatur** [danymat/neogen#36]
I would suggest to add `:Generate` command with possibility to pass an argument for type, like `func`.

**Comment by danymat** [comment]
It's a good idea, however I would like to extend the currently defined `:Neogen`, that generates default type, which is `func`.

The idea would be to allow:
- `:Neogen` (default type)
- `:Neogen func`
- `:Neogen class` 
- etc..

But I don't know personally how to allow 0 or more parameters. 😣

**Comment by Shatur** [comment]
> I would like to extend the currently defined :Neogen, that generates default type, which is func.

Sounds great.

> But I don't know personally how to allow 0 or more parameters. persevere

You looking for `-nargs=?` parameter. See `:h command-nargs`.

**Comment by danymat** [comment]
Thanks for the tip, can you try it out ?

**Comment by Shatur** [comment]
Thank you!

**Comment by Shatur** [comment]
I have another suggestion. How about to add completion to this command with available arguments?

**Comment by danymat** [comment]
Really good suggestions ! It should work right now. 

I'm thinking of providing the custom list for available types in a filetype. 
For example, Lua accepts `type, class, func, fie`, cpp accepts `func, file` (at the moment).
What do you think ? I'm worried it will disturb users

**Comment by Shatur** [comment]
> I'm thinking of providing the custom list for available types in a filetype.

Sounds like a good idea!

**Comment by danymat** [comment]
What do you think ? Can you try it out ?

**Comment by Shatur** [comment]
Awesome! Maybe disable completion if the current filetype is not supported? And throw `vim.notify` about it.

**Comment by Shatur** [comment]
Some other suggestions:
* You don't need to use `vim.tbl_keys`, just return the list as is, it should work.
* Could you add a third argument to `vim.notify` with `{title = "Neogen"}`? It allows filter messages and display it nicely with other plugins. I usually use [a helper function](https://github.com/Shatur/neovim-cmake/blob/6a0c8b353175289daf1de2d8226d99180563d10e/lua/cmake/utils.lua#L15) with predefined title that I use across the plugin.

**Comment by danymat** [comment]
Nice, will do the same

**Comment by danymat** [comment]
Is it okay ?

**Comment by Shatur** [comment]
Awesome, thank you a lot!

**Comment by danymat** [comment]
No problem, I too will use this a lot ! By the way, can you take a look at #37 when you have some time ? I need some feedback for displaying supported conventions
