### ISSUE TITLE
Better display of Support Languages

### ISSUE THREAD

**Issue by danymat** [danymat/neogen#37]
I want to change this table already present here: https://github.com/danymat/neogen#supported-languages

<img width="856" alt="Capture d’écran 2022-01-11 à 13 44 08" src="https://user-images.githubusercontent.com/5306901/148944775-4301db3a-6fb9-4804-b421-063360deb6ad.png">

With a table more minimalist and pleasant for the eyes.

If you have any ideas, feel free to feedback.

**Comment by Shatur** [comment]
The current table looks nice to me, I wouldn't change anything.
But you could be interested in nested tables. You can achieve it by putting html-table inside a markdown table cell.

**Comment by danymat** [comment]
Updated with #42
