### ISSUE TITLE
python `google_docstring` broken

### ISSUE THREAD

**Issue by meijieru** [danymat/neogen#41]
For the following code
```python
def get_all_files(directory: str) -> List[str]:
```

Currently generating
```
    """
    	directory (str): 

    Returns: 
    	
    """
```

It misses the `Args:` line before `directory`.

**Comment by danymat** [comment]
Hello, this seems to be fixed, can you try it ?

**Comment by danymat** [comment]
There are still some inconsistencies, I'm trying to fix them

**Comment by danymat** [comment]
Python should be okay now

**Comment by aurelg** [comment]
Using a03cbd1 here, same issue. What would you need for me to help? :-)

**Comment by danymat** [comment]
Hello @aurelg, can yo try again ? I think I fixed it !

**Comment by aurelg** [comment]
Many thanks, `Args:` is back where it should be!

```python3
def toto(name: str) -> int:
    """

    Args:
    	name (str): 
    """
    pass
```

BTW, shouldn't `Returns:` be here as well? :thinking:

**Comment by danymat** [comment]
> BTW, shouldn't Returns: be here as well? 

No, from the standards, Returns should only be here if there's a return type inside the function.

**Comment by danymat** [comment]
> I thought it would use type hints

Hmm, it can, and should be relatively easy to do. 
By the way, supporting type hints in return types can be a little problematic, when we have multiple returns in the function:
```py
def test() -> int:
  if 1:
    return hello
  else:
    return good_bye
```

What would be the generated annotation for it ?

**Comment by aurelg** [comment]
Good point.

My guess would be to stick to the type hint annotation in the function signature, i.e. `int`, because:
- the function signature is already the source of truth for function parameters, and
- inferring the types of `hello` and `good_bye`, as well as their consistency with type hints both in the function signature or within its body, usually fall under the responsibility of a dedicated tool, such as `mypy` or `pyright`

That being said, having typed returns would be the cherry on the cake: a nice improvement, but certainly not mandatory :blush:

**Comment by equalis3r** [comment]
I agree with @aurelg The typehint in the function signature is the contract and mypy/pyright will detect if programmer violates such contract. Let's say `hello`'s type is `int` and `good_byte` type is `str`. To not be yelled at by `mypy`, my return in the function signature needs to be: `Union[int, str]` or with python3.10 and above, `int | str`. As long as the plugin parses the function signature correctly, it's the programmers' responsibility to ensure that their written contract is upheld.

**Comment by danymat** [comment]
> That being said, having typed returns would be the cherry on the cake: a nice improvement, but certainly not mandatory 😊

I mean, it's possible, it's just that I don't know what is the desired output.
Can you guys provide me the desired annotation of the example function ?

**Comment by equalis3r** [comment]
Here is an example that I can think of. Hope it can help.

- Function with only 1 return

```
def compare(param1: int, param2: int) -> bool:
    """Example function with types documented in the docstring.

    Parameters
    ----------
    param1 : int
        The first parameter.
    param2 : int
        The second parameter.

    Returns
    -------
    bool
        True if successful, False otherwise.
    """
    return param1 == param2
```

- Function with multiple returns

```
def valid_floor_div(param1: int, param2: int) -> Union[str | int]:
    """Example function with types documented in the docstring.

    Parameters
    ----------
    param1 : int
        The first parameter.
    param2 : int
        The second parameter.

    Returns
    -------
    Union[str | int]
        str if non-zero division, int otherwise.
    """
    if param2 == 0:
        return "The divisor must be non-zero"
    else:
        return prama1 / param2
```

**Comment by danymat** [comment]
So the signature hint should override the return statements in the code (if any) ?

**Comment by aurelg** [comment]
I'd say so, yes :-)

**Comment by meijieru** [comment]
Currently, it directly says `Language python not supported` lol.

**Comment by danymat** [comment]
Hmm can you try closing neovim and going again on the file ? If it does not work, press `:e`

**Comment by meijieru** [comment]
Problem solved on latest commit, thanks!
