### ISSUE TITLE
lua configuration: function annotation doesn't work for all cases

### ISSUE THREAD

**Issue by FollieHiyuki** [danymat/neogen#43]
`:Neogen func` currently only works in this case for me
```lua
local a = function(b, c)
end
```

I added `function_declaration` to the list in https://github.com/danymat/neogen/blob/main/lua/neogen/configurations/lua.lua and make theses work
```lua
local function a(b,c)
end

function a(b, c)
end
```

The last case is `a = function(b,c) end` also doesn't work. The node for it is `function_definition` but in the configuration file it is limited to 'local' type only. Is this intentional?

For context, I'm using Neovim v0.6.1 and TreeSitter v0.20.4 in Alpine. I'm not familiar with Treesitter so this issue might be just my confusion. Sorry if that is the case!

**Comment by danymat** [comment]
Hello, thanks for providing such input ! nvim-treesitter recently updated the Lua parser, so it broke the Lua annotations. I tried to fix the missing portages between the versions, but it seems that I missed some :laughing

**Comment by FollieHiyuki** [comment]
I pulled the commit. Function annotation is working correctly now.

Thanks for the quick fix. Closing.
