### ISSUE TITLE
Support for Vue Single-File Components

### ISSUE THREAD

**Issue by zeitchef** [danymat/neogen#44]
I'd love to have support for generating docs inside Vue single-file components. Thanks for your consideration!

**Comment by danymat** [comment]
Hello ! I think that already possible, as vue is basically a mix between HTML and Js
Can you try out ? 
If it does not work, can you provide me a simple vue file I could work on ?

**Comment by danymat** [comment]
Hello, I just added support for vue with 71a92a7d, can you try it out ?

**Comment by zeitchef** [comment]
Sorry for my late reply, after the update I can confirm this is working for me in Vue SFC. Many thanks!
