### ISSUE TITLE
Update vim help!

### ISSUE THREAD

**Issue by ur4ltz** [danymat/neogen#48]
Update vim help.

**Comment by danymat** [comment]
Hello, what do you mean ?

**Comment by ur4ltz** [comment]
synchronization with README.md

**Comment by danymat** [comment]
Oh, the vim help file is custom generated from the code, and will provide detailed informations, more than the README. 
I prefer the readme to be only about exposing features and simple setup, and the vim help to be a more detailed help, with help for people who want to customize Neogen a bit more.

By the way, the Neogen help file is auto generated with mini.doc, and it allows to be very precise in what I want to expose
