### ISSUE TITLE
cpp: struct not treathed as class

### ISSUE THREAD

**Issue by JanValiska** [danymat/neogen#55]
In c++ language the `struct` is basically `class` with all members marked as public by default.

But neogen doesn't annotate `struct` as class.

Treesitter parse structs as `struct_specifier` but neogen annotates only `class_specifier` nodes as classes.
For c++ languages neogen should threat also `struct_specifier` nodes as classes.

Sorry for my cryptic english but I suppose you got a point here :D

Thank you.

**Comment by danymat** [comment]
Hello ! can you try again with latest commit ?

**Comment by JanValiska** [comment]
Works! Thank you!
