### ISSUE TITLE
python: `typed_default_parameter` not generated

### ISSUE THREAD

**Issue by xiyaowong** [danymat/neogen#60]
![neogen](https://user-images.githubusercontent.com/47070852/151977928-0ae18fb2-38bb-495a-b36c-47689bbb2c5a.gif)

using default configuration

**Comment by danymat** [comment]
Thanks for the feedback, can you try again ?

**Comment by xiyaowong** [comment]
It's working fine now. But the order of the generated code is different from the original one, can this be fixed?

```python
def test(a, b: str, c: int, d: int = 1, e: str = 'd', f=1) -> str:
    """

    Args:
        a ():
        f ():
        b (str):
        c (int):
        d (int):
        e (str):

    Returns:

    """
    print(a, b, c, d, e, f)
    return 'test'
```

**Comment by danymat** [comment]
This unfortunately cannot be fixed, because when we query tree-sitter nodes, we query them by type 😞

**Comment by xiyaowong** [comment]
maybe handle the node postion
