### ISSUE TITLE
Refactoring codebase

### ISSUE THREAD

**Issue by kevinhwang91** [danymat/neogen#61]
It sounds harsh, but I like the idea of this plugin. If you don't mind, I will make a PR with help.

**Comment by danymat** [comment]
No, the code is a little bit messy lol (I did not have a good understanding of Lua at the time)
I think the code that is messy is really inside the granulator and generator, so maybe we could start from there.
I'm currently improving the templates part, and providing some docs and API for it.

Feel free to open a PR, and let me know what do you plan to refactor ;)
Thanks for your contribution !

**Comment by kevinhwang91** [comment]
I'm looking `cursor.lua`, just using a singleton table for the positions is enough. Using extmarks is overkilled, less stable, and has more side-effects for Neovim.

**Comment by danymat** [comment]
Sure, thanks for your contribution ! 💯

**Comment by kevinhwang91** [comment]
Are you using extmarks because you want to support inserting a new line for the comments?

**Comment by danymat** [comment]
What do you mean exactly ?

**Comment by kevinhwang91** [comment]
Once the template is generated, the positions are computed that are immutable, but the position of extmarks are mutable.

`:h extmarks`

> Extended marks (extmarks) represent buffer annotations that track text changes
in the buffer. They can represent cursors, folds, misspelled words, anything
that needs to track a logical location in the buffer over time.

**Comment by danymat** [comment]
Oh yeah, I use extmarks because we can jump between annotation types even after we create some annotation and modify the lines

**Comment by danymat** [comment]
No problem, take your time, feel free to ping me if you need anything

**Comment by kevinhwang91** [comment]
Why https://github.com/danymat/neogen/blob/271260c2d805e0912939450d9b781043a72d59cb/lua/neogen/generators/default.lua#L96 may be a function type? I can't find and grep any information about this.

**Comment by danymat** [comment]
> Why
> 
> https://github.com/danymat/neogen/blob/271260c2d805e0912939450d9b781043a72d59cb/lua/neogen/generators/default.lua#L96
> 
> may be a function type? I can't find and grep any information about this.

Yes, during initial development it was assumed we could pass templates as functions, but I guess we'll not use them anymore. Even the granulator and generator, I'm not really found of creating your own.
Maybe we could simplify the process by making granulator and generator a default one, and only make templates and locators modifiable. 
Because right now, the generator is used everywhere and with some special options..

**Comment by kevinhwang91** [comment]
> > Why
> > https://github.com/danymat/neogen/blob/271260c2d805e0912939450d9b781043a72d59cb/lua/neogen/generators/default.lua#L96
> > 
> > may be a function type? I can't find and grep any information about this.
> 
> Yes, during initial development it was assumed we could pass templates as functions, but I guess we'll not use them anymore. Even the granulator and generator, I'm not really found of creating your own. Maybe we could simplify the process by making granulator and generator a default one, and only make templates and locators modifiable. Because right now, the generator is used everywhere and with some special options..

Thanks, refactor is going to be done, WIP in my local repo.
