### ISSUE TITLE
functions inside of table receive improper doc placement

### ISSUE THREAD

**Issue by mcauley-penney** [danymat/neogen#63]
It appears that, when attempting to use Neogen on a function inside of a table in Lua, the function documentation is placed above the table itself

![neogen_issue](https://user-images.githubusercontent.com/59481467/152448260-9dda5ed0-55e9-406f-8ed5-6c8131122687.gif)

**Comment by danymat** [comment]
Hello, indeed this use case was not supported. Can you try it out ?

**Comment by mcauley-penney** [comment]
Sure, I'll try it out 👍🏻 I'll try and familiarize myself with the source code today
