### ISSUE TITLE
Commit #e176773 broke ruby support

### ISSUE THREAD

**Issue by metalelf0** [danymat/neogen#68]
Hi, first of all - thanks a lot for your amazing project!

I noted that after the commit above ruby support has been broken. I bisected the bug down to that specific commit; before, it was working, when pulling that commit however I get "Language ruby is not supported".

Not doing anything fancy when setting it up, just this: `use {'danymat/neogen', config = function() require('neogen').setup { enabled = true } end }`. Let me know if you need any additional information.

Thanks again and keep up the great work!

**Comment by danymat** [comment]
Hello ! Indeed, I forgot to change the module name, so the configuration was failing. After merging the PR, it should be good to go

**Comment by metalelf0** [comment]
Hey @danymat , yes, I can confirm it's working right now.

Thanks! :)
