### ISSUE TITLE
Kotlin (KDoc) not working properly

### ISSUE THREAD

**Issue by ObserverOfTime** [danymat/neogen#78]
Class docs aren't being generated (unless explicitly specified) and function docs only output the params.

### Expected output

`…` denotes the tabstops.

```kotlin
/**
 * …
 *
 * @param T …
 * @property x …
 * @constructor …
 */
class foo<T>(val x: String) {
    /**
     * …
     *
     * @param y …
     * @return …
     */
    fun bar(y: T): Int
}

/**
 * …
 *
 * @receiver …
 * @return …
 */
fun foo.baz(): Boolean
```

The [`@constructor`][constructor] and [`@receiver`][receiver] tags are not necessary and can be skipped.

[constructor]: https://kotlinlang.org/docs/kotlin-doc.html#constructor
[receiver]: https://kotlinlang.org/docs/kotlin-doc.html#receiver

### Actual output

Commands:
- `Neogen class` on `foo`
- `Neogen` on `bar`
- `Neogen` on `baz`

```kotlin
/**
 * …
 *
* @property x …
 */
class foo<T>(val x: String) {
    /**
     * …
     *
     * @param y …
     */
    fun bar(y: T): Int
}

/**
 * …
 */
fun foo.baz(): Boolean
```

The `@property` tag is also misaligned.

**Comment by danymat** [comment]
> Class docs aren't being generated (unless explicitly specified

This behavior is normal, see Readme (Neogen will by default trigger Neogen func). You can check https://github.com/danymat/neogen/pull/74 about a way to find automatically the best upper node.

Apart from this, I'll fix these issues

**Comment by danymat** [comment]
@ObserverOfTime is a function with no return type valid ? like this:

```kotlin
fun foo.baz()
```

**Comment by ObserverOfTime** [comment]
Basically, you only want to skip the `@return` tag on a block function with no explicit return type.

```kotlin
// skip
fun foo() { ... }

// don't skip
fun foo(): T { ... }

// don't skip
fun foo() = ...

// don't skip
fun foo(): T = ...
```

In truth, the logic can get much more complicated, but this is generally fine.

**Comment by danymat** [comment]
Right, I will try to come up with a solution.

This seems more difficult than it seems, because you can see here:

![Capture d’écran 2022-03-08 à 23 01 03](https://user-images.githubusercontent.com/5306901/157332984-c5fd7aa6-7ad7-41ce-b5f4-b960e4988894.png)

Generate these nodes:

![Capture d’écran 2022-03-08 à 23 01 13](https://user-images.githubusercontent.com/5306901/157333006-eda4ff6a-9d15-4a77-a613-1ed807879081.png)

The only way to know we have a return type is by checking for a `user_type`, which can be created when we do `foo.bar` lol

**Comment by ObserverOfTime** [comment]
Kotlin's tree-sitter parser is mediocre at best (still better than its language server).
For extension functions, the first `user_type` is in fact the `@receiver`.

You could just not bother with any of the logic and always output `@return`.
At least until the parser is improved and is actually usable.

**Comment by danymat** [comment]
Hello, can you try the changes ?

**Comment by ObserverOfTime** [comment]
Only thing missing now is type parameters.

```kotlin
/**
 * class_declaration -> type_parameters -> type_parameter
 *
 * @param T
 */
class foo<T>()

/**
 * function_declaration -> type_parameters -> type_parameter
 *
 * @param T
 */
fun <T> bar()
 ```

**Comment by danymat** [comment]
Should be supported now

**Comment by ObserverOfTime** [comment]
Thanks. :+1:
