### ISSUE TITLE
TypeScript docs duplicate `@returns`

### ISSUE THREAD

**Issue by ObserverOfTime** [danymat/neogen#79]
Functions and methods with generic return types get two `@returns` tags.
This issue is present in both the TSDoc and JSDoc generators.

### Expected output

```ts
/**
 * @template T - …
 * @param bar - …
 * @returns …
 */
function foo<T>(bar: any): T { return bar as T }
```

### Actual output

```ts
/**
 * @param bar - …
 * @returns …
 * @returns …
 */
function foo<T>(bar: any): T { return bar as T }
```

**Comment by danymat** [comment]
Hello, it seems to be fixed. Can you try it ?

**Comment by ObserverOfTime** [comment]
The duplication was fixed but the `@template` tag is still missing.
```
function_declaration|method_definition > type_parameters > type_parameter
```

**Comment by danymat** [comment]
Right, did not look into that

**Comment by danymat** [comment]
Can you try again ?

**Comment by ObserverOfTime** [comment]
Works great, thanks!
