### ISSUE TITLE
input_after_comment doesn't work

### ISSUE THREAD

**Issue by cryptomilk** [danymat/neogen#8]
`input_after_comment = true` doesn't work for me.

https://github.com/danymat/neogen/blob/main/lua/neogen.lua#L59 `#data` is 0 when I generate the documentation for C. And it is already 0 at https://github.com/danymat/neogen/blob/main/lua/neogen.lua#L45

**Comment by cryptomilk** [comment]
Very nice, I tried it quickly, but doesn't work for me:

```
E5108: Error executing lua neogen/lua/neogen/utilities/cursor.lua:17: attempt to call global 'P' (a nil value)
```

I can't find a P function in the code ...

**Comment by danymat** [comment]
Ouch sorry, I let a small personal variable. Should be fixed !
I added the documentation here: https://github.com/danymat/neogen#cycle-between-annotations
