### ISSUE TITLE
Feature request: support C typedef

### ISSUE THREAD

**Issue by NTBBloodbath** [danymat/neogen#80]
Hey dany, I've found that C `typedef` aren't supported by neogen yet and it would be awesome to have support for them.

Here is an example of the TreeSitter node for `typedef`s and also doxygen docs about how should `typedef` documentation look.

![imagen](https://user-images.githubusercontent.com/36456999/157708095-a0654a81-c98a-4f1c-9fdf-58705efa6c92.png)

- [Doxygen Manual | typedef](https://www.doxygen.nl/manual/commands.html#cmdtypedef)

Cheers

**Comment by danymat** [comment]
Hello ! can you try it out ? Just type `:Neogen type` inside the node.

For example, this is what is created:

```c
/**
 * @typedef 
 * @brief 
 *
 */
typedef struct test {
  char *name;
} my_test;
```

**Comment by NTBBloodbath** [comment]
Hi, just tried it out and works like a charm. Thank you so much! :)
