### ISSUE TITLE
[Feature Request] Ability to specify annotation convention for `neogen.generate`

### ISSUE THREAD

**Issue by dhruvmanila** [danymat/neogen#83]
I don't know if this is possible right now as I can't seem to find any relevant documentation in the README or Vim docs.

I want to have two keymaps for multiple annotation convention. For example, in Python, we have multiple conventions which can be used and a default one can be specified in the setup function. There are projects which uses `numpydoc` and others which uses `google_docstring`, so it's useful to have such a possibility.

### Possible Solutions:

1. Parameter in the `neogen.generate` function which is used in setting up the keymaps
2. `Neogen` command arguments?

**Comment by danymat** [comment]
Hello ! Thanks for providing your feedback !

I think that this is a good idea, and I previously though about this.
We can manage to create an option `neogen.generate` function by passing a table for your language, like so: 

```lua
neogen.generate({ annotation_convention = { python = "numpydoc" }  })
```

What do you think ?

**Comment by dhruvmanila** [comment]
Yeah, that looks good 👍
