### ISSUE TITLE
The upstream deprecate ts_utils.get_node_text

### ISSUE THREAD

**Issue by denstiny** [danymat/neogen#88]
[#2833](https://github.com/nvim-treesitter/nvim-treesitter/pull/2833)
[location](https://github.com/danymat/neogen/blob/f249a70ee598bdf8d015c10536c0dcd97c79b3aa/lua/neogen/utilities/extractors.lua#L17)

**Comment by danymat** [comment]
The issue you pointed is basically: revert deprecation. So we should be good

**Comment by denstiny** [comment]
[this](https://github.com/nvim-treesitter/nvim-treesitter/commit/44b7c8100269161e20d585f24bce322f6dcdf8d2#diff-73d8fd4bc707f46576768511e62a4a2ddc0bb32f1e676b4b208e9d61e193d8acL10)
Although it can work, the upstream carried warning
```lua
function M.get_node_text(node, bufnr)
  vim.notify_once(
    "nvim-treesitter.ts_utils.get_node_text is deprecated: use vim.treesitter.query.get_node_text",
    vim.log.levels.WARN
  )
  return get_node_text(node, bufnr)
end
```

**Comment by jemag** [comment]
It is still being deprecated. I think what was reverted was a wrapper that made `ts_utils.get_node_text` silently call `vim.treesitter.query.get_node_text` behind the scenes. Both functions are not exactly the same, so they reverted that wrapper.

My understanding is that people/plugins should still move to `vim.treesitter.query.get_node_text`

**Comment by denstiny** [comment]
> 
In favor of

**Comment by fgheng** [comment]
I meet the same question
![image](https://user-images.githubusercontent.com/50551377/166300000-ad3ca9dd-a633-4260-8f88-ce5082c5c1de.png)

**Comment by krishnakumarg1984** [comment]
I get the same error when running `:Neogen`
![image](https://user-images.githubusercontent.com/15239509/167154861-c6db89db-49dd-4427-907d-a144c91e48e5.png)

**Comment by denstiny** [comment]
> 发出相同的警告 `:Neogen`命令 ![image](https://user-images.githubusercontent.com/15239509/167154861-c6db89db-49dd-4427-907d-a144c91e48e5.png)

Did you solve?

**Comment by krishnakumarg1984** [comment]
No. Same warning message still.

**Comment by denstiny** [comment]
> 不。仍然有相同的警告信息。

https://github.com/nvim-treesitter/nvim-treesitter/commit/44b7c8100269161e20d585f24bce322f6dcdf8d2#r73108137

**Comment by krishnakumarg1984** [comment]
Works now

**Comment by ranebrown** [comment]
Can this be done?
```patch
diff --git a/lua/neogen/granulator.lua b/lua/neogen/granulator.lua
index 616ad37..65be7cd 100644
--- a/lua/neogen/granulator.lua
+++ b/lua/neogen/granulator.lua
@@ -34,7 +34,12 @@ return function(parent_node, node_data)
                         end
                     else
                         -- if not extract function, get the text from the node (required: data.type)
-                        result[data.type] = ts_utils.get_node_text(child_node)
+                        local gnt = vim.treesitter.query.get_node_text
+                        if gnt ~= nil then
+                            result[data.type] = gnt(child_node)
+                        else
+                            result[data.type] = ts_utils.get_node_text(child_node)
+                        end
                     end
                 end
             end
diff --git a/lua/neogen/utilities/extractors.lua b/lua/neogen/utilities/extractors.lua
index aed0b31..9854ac7 100644
--- a/lua/neogen/utilities/extractors.lua
+++ b/lua/neogen/utilities/extractors.lua
@@ -14,7 +14,12 @@ return {
                 return node:type()
             end
             local get_text = function(node)
-                return ts_utils.get_node_text(node)[1]
+                local gnt = vim.treesitter.query.get_node_text
+                if gnt ~= nil then
+                    return gnt(node)
+                else
+                    return ts_utils.get_node_text(node)[1]
+                end
             end
             if opts.type then
                 result[k] = vim.tbl_map(get_type, v)
```

**Comment by askfiy** [comment]
some

**Comment by danymat** [comment]
Hello, can you people try last PR ? If everything is okay, I merge to main

**Comment by jemag** [comment]
@danymat works for me.
