### ISSUE TITLE
Add options for languages with multiple comment types

### ISSUE THREAD

**Issue by AlxHnr** [danymat/neogen#90]
Neogen generates C++ comments like these:

```cpp
/*
 * @brief
 *
 * @param foo
```

But certain C++ projects mandate this style:

```cpp
///
/// @brief
///
/// @param foo
```
It would be great if this behavior would be configurable. Here are two possible solutions:
1. Parse `commentstring`, which is used by various comment plugins and by vim itself. This leads to a more consistent experience
2. Provide different templates

**Comment by danymat** [comment]
Hello, we can create a new template for this, should be really easy to do so

**Comment by danymat** [comment]
Hello, I don't quite get what you're expecting. Do you want to provide multiple options for languages, or add a new template to C++ ?

Because the former is already in place, and you can provide multiple templates for a single language (check Readme). If you wanna create a new template, you can see `:h neogen-annotation`

**Comment by AlxHnr** [comment]
Providing more templates for each variation would be too much effort. It would be better to parse `commentstring` and add a few extra settings to distinguish between `/// @brief ...`, `//! @brief` and so on. I'm not sure what the most common styles are, but they should be configurable.

**Comment by danymat** [comment]
Really, it is not ! The capability is already there, and we should just create a new template for it. 

But for the variations you pointed here, as they are not custom annotations, I think the best is to create your own annotation convention on the fly and add it to your setup.

**Comment by AlxHnr** [comment]
You are right. I just saw in the docs that I can just create custom annotation setups in my init.lua for C++.

But would it make sense to extend the default C++ template to consider `commentstring`? Many other plugins use this setting to decide which comment style to use. E.g. [vim-commentary](https://github.com/tpope/vim-commentary) or [nvim-ts-context-commentstring](https://github.com/JoosepAlviste/nvim-ts-context-commentstring).
