### ISSUE TITLE
Docstring for javadoc does not include exception names

### ISSUE THREAD

**Issue by dwoznicki** [danymat/neogen#91]
For javadoc docstrings, there is only one throws line generated and it does not include the exception names.

### Current behavior
Here's a sample function + generated docstring.
```java
public class Testo {
    /**
     * [TODO:description]
     *
     * @param one [TODO:parameter]
     * @return [TODO:return]
     * @throws [TODO:throw]
     */
    public String get(String one) throws NullPointerException, RuntimeException {
        return "";
    }
}
```

### Expected behavior
This isn't wrong, but it could be better. Typically, javadoc docstrings have [one line per exception thrown](http://www.javapractices.com/topic/TopicAction.do?Id=171).

Generating the following docstring would be nice.
```java
public class Testo {
    /**
     * [TODO:description]
     *
     * @param one [TODO:parameter]
     * @return [TODO:return]
     * @throws NullPointerException [TODO:throw]
     * @throws RuntimeException [TODO:throw]
     */
    public String get(String one) throws NullPointerException, RuntimeException {
        return "";
    }
}
```

### Possible solution
It looks like the exception names are present in the TreeSitter tree, but I don't quite understand how neogen chooses what nodes to extract. In case it's helpful, here's what the tree roughly looks like in my actual file.

```
    method_declaration [25, 4] - [57, 5]
      modifiers [25, 4] - [25, 17]
      type: type_identifier [25, 18] - [25, 26]
      name: identifier [25, 27] - [25, 37]
      parameters: formal_parameters [25, 37] - [25, 52]
        formal_parameter [25, 38] - [25, 51]
          type: type_identifier [25, 38] - [25, 44]
          name: identifier [25, 45] - [25, 51]
      throws [25, 53] - [25, 99]
        type_identifier [25, 60] - [25, 81]
        type_identifier [25, 83] - [25, 99]
```

In the `throw` node, the exception names are the `type_identifier` s.

**Comment by dwoznicki** [comment]
Works as expected on branch `throws-statement-java`. Nice!

**Comment by danymat** [comment]
It should be on main by now !
